/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


examples:

find_the_difference("aaa", "abaac") == "bc"
find_the_difference("","") == ""
find_the_difference("abc", "azbscd") == "zsd"
find_the_difference("", "abc") == "abc"
find_the_difference("abcde", "") == ""
find_the_difference("y", "yz") == "z"
find_the_difference("abc", "abc") == ""

Problem/ Test Cases
Rules:
- return the one letter present in t string that isn't present in s string
- if t string is empty return empty string
- if s string is empty return t string

Input: strings
Output: string
Data Structure: array;

Algo:
- Guard clauses 
  if s is empty return t
  if t is empty return empty string
- split t string into array of chars
- iterate over s string
  - find location of current char in t string and remove it
- return t arr joined as string

*/

function findTheDifference(s, t) {
  if (s.length === 0) return t;
  if (t.length === 0) return '';

  let tArr = t.split('');

  s.split('')
   .forEach(char => {
     tArr.splice(tArr.indexOf(char), 1)
   });

   return tArr.join('');
}

console.log(findTheDifference("abc", "azbscd"))
